### ISSUE TITLE
[Question] What happens to the backup/log if router loses power? Will the new file overwrite all the previously-kept data?

### ISSUE THREAD

**Issue by hub2git** [jow-/nlbwmon#10]
Let's say my nlbwmon program is happily doing daily backups of the bandwidth for August 1 through 15 to the USB stick inserted on the back of the router.  

On August 20, there is a power outage to the city and the router abruptly loses power. There is no power for a few days (Aug 20 through 24). On Aug. 25, power is restored and the router is powered on. What happens from Aug. 25 onwards?  When nlbwmon tries to backup to the USB stick, will it overwrite the data from Aug. 1 through 15? In other words, will the USB stick now contain just August 25 onwards?

Or will the USB stick -- this is my hope -- contain Aug 1-15 **and** Aug. 25 onwards?

**Comment by jow-** [comment]
nlbwmon attempts to import the last archived database into its scratch space and will append new data to it.
