### ISSUE TITLE
can I disable ipv6 stats

### ISSUE THREAD

**Issue by rezad1393** [jow-/nlbwmon#16]
is it possible to disable ipv6 in statistics ?
I don't have any ipv6 connectivity on WAN side.
and I want to log the WAN side only.

also I have lede installed on a router and the router is connected to internet via bridge to a modem.
how do I log the traffic consumption for internet?
the router has the physial interfaces as eth0 and eth1.
eth1 is lan and eth0 in the Ethernet that I have connected as bridge to modem(so that I wouldn't have to port forward on the modem too and all that.)
should I just disable bridge and connect via lan to modem? that way the internet traffic accounting would be easier?

**Comment by jow-** [comment]
In order to stop tracking IPv6 statistics, only specify the IPv4 range of your local network and deselect all tracking interfaces.
