### ISSUE TITLE
port range?

### ISSUE THREAD

**Issue by rezad1393** [jow-/nlbwmon#17]
can I specify a port range instead of one port?

**Comment by jow-** [comment]
Kind of, you can specify multiple consecutive (!) entries with one port each which will be grouped into one layer7 protocol, see e.g. the existing NetBios examples.

    # custom protocol spanning ports 10000-10010
    6 10000 CustomProto
    6 10001 CustomProto
    6 10002 CustomProto
    6 10003 CustomProto
    6 10004 CustomProto
    6 10005 CustomProto
    6 10006 CustomProto
    6 10007 CustomProto
    6 10008 CustomProto
    6 10009 CustomProto
    6 10010 CustomProto


Specifying ranges directly is not supported at the moment.

**Comment by rezad1393** [comment]
and if I want to add an application that want to have 30 port range then I have to add those 30 manually?
maybe this should be considered as an feature to be added?
