### ISSUE TITLE
Error in building lede trunk with uClibc

### ISSUE THREAD

**Issue by ss-plus** [jow-/nlbwmon#2]
**Error information:**
make[3]: Entering directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e'
make[4]: Entering directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e'
make[5]: Entering directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e'
Scanning dependencies of target nlbwmon
make[5]: Leaving directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e'
make[5]: Entering directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e'
[  9%] Building C object CMakeFiles/nlbwmon.dir/client.c.o
[ 18%] Building C object CMakeFiles/nlbwmon.dir/database.c.o
[ 27%] Building C object CMakeFiles/nlbwmon.dir/neigh.c.o
In file included from /home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/netlink.h:30:0,
                 from /home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/msg.h:15,
                 from /home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e/neigh.c:29:
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/handlers.h:134:19: error: 'struct ucred' declared inside parameter list [-Werror]
            struct ucred **);
                   ^
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/handlers.h:134:19: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/handlers.h:208:36: error: 'struct ucred' declared inside parameter list [-Werror]
           unsigned char **, struct ucred **))
                                    ^
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/handlers.h: In function 'nl_cb_overwrite_recv':
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/handlers.h:210:17: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
  cb->cb_recv_ow = func;
                 ^
In file included from /home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/msg.h:15:0,
                 from /home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e/neigh.c:29:
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/netlink.h: At top level:
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/netlink.h:57:13: error: 'struct ucred' declared inside parameter list [-Werror]
      struct ucred **);
             ^
In file included from /home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e/neigh.c:29:0:
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/msg.h:52:16: error: field 'nm_creds' has incomplete type
  struct ucred  nm_creds;
                ^
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/msg.h: In function 'nlmsg_set_creds':
/home/everun/build/lede/trunk/source/staging_dir/target-arm_cortex-a9_uClibc_eabi/usr/include/libnl-tiny/netlink/msg.h:207:39: error: dereferencing pointer to incomplete type 'struct ucred'
  memcpy(&msg->nm_creds, creds, sizeof(*creds));
                                       ^
cc1: all warnings being treated as errors
make[5]: *** [CMakeFiles/nlbwmon.dir/neigh.c.o] Error 1
make[5]: Leaving directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e'
make[4]: *** [CMakeFiles/nlbwmon.dir/all] Error 2
make[4]: Leaving directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e'
make[2]: *** [/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a9_uClibc_eabi/nlbwmon-2017-07-28-76487b5e/.built] Error 2
make[2]: Leaving directory `/home/everun/build/lede/trunk/source/feeds/packages/net/nlbwmon'
make[1]: *** [package/feeds/packages/nlbwmon/compile] Error 2
make[1]: Leaving directory `/home/everun/build/lede/trunk/source'
make: *** [package/feeds/packages/nlbwmon/compile] Error 2

**Comment by ss-plus** [comment]
**new error information:**
make[3]: Entering directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02'
make[4]: Entering directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02'
make[5]: Entering directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02'
Scanning dependencies of target nlbwmon
make[5]: Leaving directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02'
make[5]: Entering directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02'
[  9%] Building C object CMakeFiles/nlbwmon.dir/client.c.o
[ 18%] Building C object CMakeFiles/nlbwmon.dir/database.c.o
[ 27%] Building C object CMakeFiles/nlbwmon.dir/neigh.c.o
/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02/neigh.c:28:0: error: "_GNU_SOURCE" redefined [-Werror]
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
cc1: all warnings being treated as errors
make[5]: *** [CMakeFiles/nlbwmon.dir/neigh.c.o] Error 1
make[5]: Leaving directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02'
make[4]: *** [CMakeFiles/nlbwmon.dir/all] Error 2
make[4]: Leaving directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02'
make[2]: *** [/home/everun/build/lede/trunk/source/build_dir/target-arm_cortex-a15+neon-vfpv4_uClibc_eabi/nlbwmon-2017-08-02/.built] Error 2
make[2]: Leaving directory `/home/everun/source/everun/2.applications/nlbwmon/2017-08-02/nlbwmon'
make[1]: *** [package/everun/general/nlbwmon/compile] Error 2
make[1]: Leaving directory `/home/everun/build/lede/trunk/source'
make: *** [package/everun/general/nlbwmon/compile] Error 2

**Comment by jow-** [comment]
Already fixed in the next commit.
