### ISSUE TITLE
Running nlbwmon package on Openwrt CC

### ISSUE THREAD

**Issue by sanaBA** [jow-/nlbwmon#24]
Hi,

I compiled and deployed the nlbwmon package on my router running Openwrt chaos calmer (I created my own Makefile to be able to compile the package).
When I start it via cli, I get the following error:
nlbwmon
No interval specified; assuming 1st of month
Unable to read protocol list /usr/share/nlbwmon/protocols: No such file or directory
Apparently, I need to create a file with the list of protocols. Can you please specify the list of config options needed to have it working correctly? do I need to specify the database-folder?
How can I also use the client utility (nlbw) in order to query the daemon for current statistics?

Thank you

**Comment by jickding** [comment]
try lede nlbwmon package. all file in it.

**Comment by jow-** [comment]
- The usage is explained in https://github.com/jow-/nlbwmon/blob/master/README.md
- An example protocols file can be found at https://github.com/jow-/nlbwmon/blob/master/protocols.txt
