### ISSUE TITLE
No internet 

### ISSUE THREAD

**Issue by berlusconi500** [jow-/nlbwmon#29]
I'm using this software on a router with OpenWRT but I can't log the traffice to/from the internet. This is my configuration:

config nlbwmon
        option commit_interval '24h'
        option refresh_interval '30s'
        option database_directory '/var/lib/nlbwmon'
        option database_generations '10'
        option database_interval '1'
        option database_limit '10000'
        option protocol_database '/usr/share/nlbwmon/protocols'
        list local_network '0.0.0.0/0'
        list local_network 'bridge'

eth0 and eth1 are configured with a DHCP bridge.
Do I have to specify individual interfaces or do I need to specify the bridge?

**Comment by jow-** [comment]
The `local_network` must correspond to the IP address range used on your lan, e.g. `192.168.1.0/24` since it is used to differentiate incoming and outgoing request. With `0.0.0.0/0`, *any* traffic will be treated as local to local and will not get counted.

**Comment by berlusconi500** [comment]
Thanks for your quick response

Okay, I set 192.168.0.0/16 as a subnet but I still don't see the traffic to the internet, only the local one. Am I doing something wrong or is nlbwmon not the software that does it for me?

I'm looking for a software that logs me traffic and ip addresses in forwarding on the router and I was advised this for its clearly better performance than iptables log

**Comment by jow-** [comment]
I am not sure what you expect to see but this software will count and aggregate outbound traffic per lan host. Maybe this is not what you're looking for.
