### ISSUE TITLE
[feature]Add similar to littlesnitch to show the region where the router initiated the link on the map

### ISSUE THREAD

**Issue by peterwillcn** [jow-/nlbwmon#37]
Add similar to littlesnitch to show the region where the router initiated the link on the map
![littlesnitch-monitor-screenshot](https://user-images.githubusercontent.com/323794/77439334-df722f80-6e21-11ea-8bc8-2619423b1673.png)

**Comment by jow-** [comment]
Outside of the scope of the cli daemon
