### ISSUE TITLE
Empty result on Ubuntu 20.04 Beta

### ISSUE THREAD

**Issue by ysc3839** [jow-/nlbwmon#38]
I'm trying to run this program on Ubuntu 20.04 Beta but got empty result from `sudo nlbw -c show`.
I installed conntrack (`sudo apt-get install conntrack`) and confirm nf_conntrack is loaded (`lsmod | grep nf_conntrack`).
I set `net.netfilter.nf_conntrack_acct` to 1 according to #35, but still got empty result.
My IP address is `192.168.213.128/24` and I run nlbwmon with `sudo nlbwmon -s '192.168.0.0/16'`.
Did I miss something?

**Comment by jow-** [comment]
Is your ubuntu acting as router? Nlbwmon will only count traffic from `192.168.0.0/16` to not `192.168.0.0/16` or vice versa.

**Comment by ysc3839** [comment]
It's not a router.
I also tried OpenWrt x86-64 snapshot, set lan proto to `dhcp` and it works.
