### ISSUE TITLE
kernels update

### ISSUE THREAD

**Issue by linzianxyz** [jow-/nlbwmon#41]
Downloading https://openwrt.proxy.ustclug.org/releases/18.06.8/packages/mipsel_24kc/luci/luci-app-nlbwmon_git-20.213.35591-16dfb55-1_all.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-nlbwmon:
 *      kernel (= 5.4.60-1-d38eb031bb825d2536631cceb1dff1fa)
 * opkg_install_cmd: Cannot install package luci-app-nlbwmon.

**Comment by jow-** [comment]
Not an issue with nlbwmon. Make sure your running kernel matches the repositories.
