### ISSUE TITLE
Impossible to view details per MAC address when machine has had large number of IPs

### ISSUE THREAD

**Issue by Ziginox** [jow-/nlbwmon#42]
Probably a bit of an edge case, but due to my ISP's flakiness lately, my machines have had their IPv6 addresses changed frequently. Because of this, the popup on the Traffic Distribution tab of the luci app is impossible to read. Is there any way to pop it out into its own window, or make it scrollable otherwise?
![chrome_2020-12-13_14-29-24](https://user-images.githubusercontent.com/7716504/102024590-36bd8480-3d50-11eb-9851-abad65fe7ba0.png)

**Comment by jow-** [comment]
LuCI display issue
