### ISSUE TITLE
Nftables support

### ISSUE THREAD

**Issue by tiagogaspar8** [jow-/nlbwmon#47]
Hi!

Right now Openwrt is switching from iptables to nftables and netlink is supposed to be universal, not depending on iptables or nftables since it is an api for netfilter (even though it's dependencies are incorrect on openwrt).
I have tried bwmon on an nftables router and even though connections are correctly shown in `Status > Realtime Graphs > Connections`, in the bwmon luci page only connections from the router itself are shown and updated.

Support needs to be added with a change to this repo?

Thanks!

**Comment by jow-** [comment]
I don't think the issue is nftables specific. Maybe some kernel side dependencies are not included anymore since the switch to nftables. The netlink API being used should be the same.

**Comment by tiagogaspar8** [comment]
I see, that's what I thought... do you think it should be a symbol or something harder linke a patch needed, etc.?
Either way for now I sent a pull request to fix the netlink dependencies
https://github.com/openwrt/openwrt/pull/4986

Should this issue here be closed?

**Comment by tiagogaspar8** [comment]
I'll close this cause for me it seems that nlbwmon is supporting nftables well/correctly
Is that ok?

**Comment by schuettecarsten** [comment]
With OpenWrt 22.03.0-rc0, nwlbmon does not show any useful information. It mainly tracks upload connections from the OpenWRT router itself, but only a few download connections from the network devices. For example, after a Fire TV session, it shows 45.13 MiB upload for the stick, but only 29.85 KiB download - should be more than a few gigabytes.

![image](https://user-images.githubusercontent.com/1275166/171102065-0d318974-090d-4ca5-8a91-b3831ff341f3.png)
