### ISSUE TITLE
Non OpenWRT (amd64-linux) compile possible ?

### ISSUE THREAD

**Issue by dandudikof** [jow-/nlbwmon#48]
Was using nlbwmon on openwrt for years but missing it 
on plain linux router/firewall installs ( when openwrt does not cut it )

Ntopng seems like major overkill for simple bandwith/host tracking.
wrtbwmon relies on extra iptables rulles (which i like nice and tidy, and manageable)
(just want to track all hosts being routed trough the firewall)

Was trying to compile nlbwmon for devuan (debian without systemd) . 
But got stuck on avl.h and usock.h
Which seem to be parts of libubox (openwrt pkg only).

avl.h can be found with libavl-dev package but not usock.h 

So was wondering if you could just use avl.h and usock.h from x86openwrt on 
regular linux or any other solution that would make nlwbmon work on non openwrt linux.

Thanx

**Comment by jow-** [comment]
It should be enough to compile and install OpenWrt's libubox on your system, that's what I do to test nlbwon on Debian here.

**Comment by dandudikof** [comment]
Thank you jow for anwser , and for nlwbmon.

Can close or delete this thread , as it does not seem like a bug.
Just had to ask , and seemed like the right place.
