### ISSUE TITLE
I've installed nlbwmon to track bandwidth per billing cycle. Any reason to keep using vnstat? [question]

### ISSUE THREAD

**Issue by hub2git** [jow-/nlbwmon#5]
Dear folks, 

About a week ago, I installed nlbwmon on my router (Lede 17.01.2 is firmware) with the hopes to have a log of my bandwidth use. (I simply need to see how much bandwidth I've used for each billing month). 

Is there any reason why I should still use vnstat? In other words, is there something that vnstat does and which I need that nlbwmon doesn't do?

Thank you.

----
luci-app-nlbwmon version: git-17.217.44847-21ae7f2-1
nlbwmon version | 2017-08-02-32fc0925-1

**Comment by hub2git** [comment]
I see reason to keep vnstat installed. nlbwmon doesn't seem to accurately measure bandwidth use. Maybe it has some bugs. 

(I realize that vnstat and nlbwmon don't measure the exact same thing. I'm fine with that. But when I say nlbwmon doesn't give accurate measurements, I just mean I'm not 100% certain that nlbwmon is fulfilling its goal of counting bandwidth from local <--> remote destinations. Maybe it's because it doesn't account ipv6. I'll have to run some more tests.)

**Comment by jow-** [comment]
Closing this as it leads to nothing actionable. Latest commits might have fixed some reporting mismatches.
