### ISSUE TITLE
Why are bandwidth numbers from nlbwmon tiny, especially compared to vnstat's numbers?

### ISSUE THREAD

**Issue by hub2git** [jow-/nlbwmon#7]
Let's look solely on the wlan0 (2.4 gHz) bandwidth, which is used by only one device, a Satellite laptop.

In nlbwmon's info, the Satellite's total bandwidth is less than 300 MB.
But in vnstat, wlan0's total bandwidth is 1.42 GB.
 
Can someone kindly help me understand the discrepancy? 
Please know that both have the same billing cycle (same cutoff date).

![192 168 1 1-cgi-bin-luci-admin-status-vnstat-style m 1](https://user-images.githubusercontent.com/7141051/29450938-8f19af9e-83b5-11e7-8a40-8397806c717f.png)
![192 168 1 1-cgi-bin-luci-admin-nlbw-display 1](https://user-images.githubusercontent.com/7141051/29450939-8f2b16da-83b5-11e7-957b-cc69ccb61f93.png)

![192 168 1 1-cgi-bin-luci-admin-status-vnstat-config](https://user-images.githubusercontent.com/7141051/29451037-fad2024a-83b5-11e7-9ab2-58b679bdcfb9.png)

**Comment by jow-** [comment]
Vnstat looks at interface traffic counters which also factor in things like local broadcast traffic, protocol overhead etc. while nlbwmon solely counts connections which are destined from the local network to remote destinations.

**Comment by hub2git** [comment]
@jow- 
Thank you for replying. Based on the differences as you describe, your program, nlbwmon, is what I want.

If I understand you correctly, nlbwmon will tell me how much bandwidth I've used, **as seen from the point of view of the ISP**. Is this correct?

**Comment by jow-** [comment]
Yes, that is the basic idea.

**Comment by hub2git** [comment]
@jow- thank you again for your reply.

Could there be other reasons for the discrepancy, though? For instance, (I understand that) nlbwmon has issues monitoring ipv6 stats.

**Comment by sages** [comment]
Is there a requirement to have 'Force Connection Tracking' enabled in iptables to correct the discrepancy between vnstat and nlbwmon?

**Comment by hub2git** [comment]
@sages 

I don't want nlbwmon to have the same figures as vnstat, merely for the sake of removing the discrepancy.  Nlbwmon and vnstat measure different things. There may be overlap in what they measure, but their "nets" don't cover exactly the same "area". 


What I do wish, however, is for nlbwmon​ to fulfill its intended goal of counting the ”[connections which are destined from the local network to remote destinations](https://github.com/jow-/nlbwmon/issues/7#issuecomment-323304178)”. Because, at the moment, nlbwmon seems to be deficient in fulfilling its stated job description.
