### ISSUE TITLE
For testing purposes, can I see hourly / daily stats?

### ISSUE THREAD

**Issue by hub2git** [jow-/nlbwmon#8]
Dear @jow- 

This is simply a question, and not an issue/bug. :smile_cat: 

I am trying to verify nlbwmon's accuracy/comprehensiveness in monitoring bandwidth, and for my experiment, it would be handy if I could get a more granular view -- in other words, hourly breakdown. Is this possible? I'd love to see it in nlbwmon-luci, as I'm more comfortable with GUI, but will be okay if there is only a terminal/console way. I read the readme on https://github.com/jow-/nlbwmon, and I don't see terminal instructions.

**Comment by jow-** [comment]
A hourly breakdown is not possible at this point in time.
