### ISSUE TITLE
ipv6 issues

### ISSUE THREAD

**Issue by hub2git** [jow-/nlbwmon#9]
Dear @jow- 

A few people who have installed nlbwmon have reported issues with the tracking of ipv6 on a thread in the Lede forums.

A user named [hnyman](https://forum.lede-project.org/t/monitoring-bandwidth-used-per-user-because-metered-internet/2167/35?u=greenlaser)

And another user named [philjohn](https://forum.lede-project.org/t/monitoring-bandwidth-used-per-user-because-metered-internet/2167/39)

And a third user named [moeller0](https://forum.lede-project.org/t/monitoring-bandwidth-used-per-user-because-metered-internet/2167/41)

**Comment by philjohn** [comment]
Yep, I was seeing this, I did have the Qualcomm FastPath patch enabled, which could be a possible issue.

**Comment by jow-** [comment]
Yes. The software relies on conntrack accounting which in turn needs the ability to see each packet in order to properly count transmit volume. Anything that bypasses conntrack (NOTRACK rules, fastpath, hardware NAT accelleration) will lead to skewed results.

**Comment by hub2git** [comment]
@jow- 

Was your reply to @philjohn or to me?

Are you saying that ipv6 bypasses conntrack?
Are you saying that a 100% of ipv4  goes through conntrack?

What can/should I do to get accurate accounting? 

Would disabling ipv6 on my router help?

**Comment by hub2git** [comment]
@jow-, @philjohn

> Anything that bypasses conntrack (NOTRACK rules, fastpath, hardware NAT accelleration) will lead to skewed results.

I don't want skewed results. Can I block everything that bypasses conntrack? If so, how?

**Comment by Schabram** [comment]
Hi I have no fw rules & SFE, HWNAT that bypass conntrack.
Problem is dynamic PD change the LAN prefix and nlbwmon dont noice it.
I started a clean nlbwmon session ipv6 count with 10GB down 1 GB upload accurate 11GB displayed but after prefix change no traffic count anymore or on router reboot if nlbwmon start before lan PD prefix is set also no traffic count.
 
My setup is easy br-lan with ULA and default IPV4 (eth0.1 + wlan 2G + 5G AC) 64 prefix from wan / use only Stateless setup odhcpd, dns get ULA router address for DNS
wan with pppoe + ipv6 '1' over vlan 7  (get fe80::128) and public IPv4
wan6 '@ wan' dhcpv6 PD get 56 dynamic prefix & lan get the address everything work nice out of the box

**Comment by AndreaBorgia-Abo** [comment]
@Schabram I have a fixed prefix thanks to a he.net tunnel but I see no traffic count for IPV6 right from the start.
@jow- I am not using anything that bypasses conntrack, as far as I can see.

**Comment by jow-** [comment]
Should have been addressed by https://github.com/openwrt/packages/commit/662d3f16d2702fe55116c852f5d456e90891ee89

**Comment by naseef** [comment]
> Should have been addressed by [openwrt/packages@662d3f1](https://github.com/openwrt/packages/commit/662d3f16d2702fe55116c852f5d456e90891ee89)

My WAN interface is configured as PPPoE.  IPV6 stats of nlbwmon is not correctly reported until I do nlbwmon service stop and start
